name: CocoaPods

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '*.md'
    - 'LICENSE'
    - 'Package*.swift'
    - 'Source/SwiftPackage/**'
    - '.github/workflows/swiftpm.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '*.md'
    - 'LICENSE'
    - 'Package*.swift'
    - 'Source/SwiftPackage/**'
    - '.github/workflows/swiftpm.yml'

jobs:
  pod-lib-lint:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: ["ios", "macos", "tvos", "watchos"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v2
    # Manually expanding out static frameworks to avoid making to many jobs.
    - name: Pod lib lint
      run:  |
        pod lib lint --verbose \
          --configuration=${{ matrix.CONFIGURATION }} \
          --platforms=${{ matrix.PLATFORM }} \
          GTMSessionFetcher.podspec
    - name: Pod lib lint - Use Static Frameworks
      run:  |
        pod lib lint --verbose --use-static-frameworks \
          --configuration=${{ matrix.CONFIGURATION }} \
          --platforms=${{ matrix.PLATFORM }} \
          GTMSessionFetcher.podspec
